package com.example.travelerapp

sealed class Screen(val route: String) {

    object UserOrAdmin: Screen(route = "user_or_admin_screen")
    object Home: Screen(route = "home_screen")
    object Login: Screen(route = "login_screen")
    object Signup: Screen(route = "signup_screen")
    object UserForgotPw: Screen(route = "user_forgot_password_screen")
    object UserChangePw: Screen(route = "user_change_password_screen")
    object UserChangeUsername: Screen(route = "user_change_username_screen")
    object AddPIN: Screen(route = "addPIN_screen")
    object Review: Screen(route = "review_screen")
    object EditReview: Screen(route = "edit_review_screen")
    object UserDisplayPackageList: Screen(route = "user_display_package_list_screen")
    object UserViewTrip: Screen(route = "user_view_trip_screen")
    object UserBookingTripScreen: Screen(route = "user_booking_trip_screen")
    object UserPackagePurchased: Screen(route = "user_package_purchased")
    object UserPackageDetails: Screen(route = "user_package_details")
    object Payment: Screen(route = "payment_screen")
    object Wallet: Screen(route = "wallet_screen")
    object Transaction: Screen(route = "transaction_screen")
    object Reload: Screen(route = "reload_screen")
    object Profile: Screen(route = "profile_screen")
    object Settings: Screen(route = "settings_screen")
    object AgencyLogin: Screen(route = "agency_login_screen")
    object AgencySignup: Screen(route = "agency_signup_screen")
    object AgencyChangePw: Screen(route = "agency_change_password_screen")
    object AgencyChangeUsername: Screen(route = "agency_change_username_screen")
    object AgencyForgotPw: Screen(route = "agency_forgot_password_screen")
    object AgencyHome: Screen(route = "agency_home_screen")
    object AgencyAddPackage: Screen(route = "agency_add_package_screen")
    object AgencyPackageList: Screen(route = "agency_package_list_screen")
    object AgencyPackageDetail: Screen(route = "agency_package_detail_screen")
    object AgencyEditPackage: Screen(route = "agency_edit_package_screen")
    object AgencySetting: Screen(route = "agency_setting_screen")
}